name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensures compatibility with your project's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Ensure this is the correct region for your S3 bucket

    - name: Deploy to S3
      run: aws s3 sync build/ s3://max-win-checker --acl public-read --delete
